CREATE TABLE `orders` (
    `id`                     BIGINT       NOT NULL AUTO_INCREMENT COMMENT '订单ID',
    `user_id`                BIGINT       NOT NULL COMMENT '用户ID',
    `product_id`             BIGINT       NOT NULL COMMENT '产品ID',
    `product_name`           VARCHAR(200) NOT NULL COMMENT '产品名称（冗余快照）',
    `product_image_url`      VARCHAR(500)          DEFAULT NULL COMMENT '产品图片（冗余快照）',
    `points_cost`            INT          NOT NULL COMMENT '消耗积分',
    `status`                 VARCHAR(20)  NOT NULL DEFAULT 'PENDING' COMMENT '兑换状态: PENDING/READY/COMPLETED/CANCELLED',
    `points_transaction_id`  BIGINT                DEFAULT NULL COMMENT '积分扣除流水ID（用于取消时回滚）',
    `created_at`             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updated_at`             DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `created_by`             BIGINT                DEFAULT NULL COMMENT '创建人',
    `updated_by`             BIGINT                DEFAULT NULL COMMENT '更新人',
    `deleted`                TINYINT      NOT NULL DEFAULT 0 COMMENT '逻辑删除 0-未删除 1-已删除',
    `version`                INT          NOT NULL DEFAULT 0 COMMENT '乐观锁版本号',
    PRIMARY KEY (`id`),
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_product_id` (`product_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_created_at` (`created_at`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '兑换订单表';
